describe("cursor.config", function()
  it("has defaults", function()
    local config = require("cursor.config")
    config.setup({})
    local cfg = config.get()
    assert.equals("agent", cfg.agent_command)
    assert.equals(false, cfg.auto_start)
  end)
end)

describe("cursor.state", function()
  it("tracks rpc ids", function()
    local state = require("cursor.state")
    state.reset()
    assert.equals(1, state.next_rpc_id())
    assert.equals(2, state.next_rpc_id())
  end)
end)

describe("cursor.rpc", function()
  it("encodes requests", function()
    local rpc = require("cursor.rpc")
    local state = require("cursor.state")
    state.reset()
    local data, id = rpc.request("initialize", { protocolVersion = 1 }, function() end)
    assert.equals(1, id)
    assert.truthy(data:find("initialize"))
  end)

  it("handles responses", function()
    local rpc = require("cursor.rpc")
    local state = require("cursor.state")
    state.reset()
    local called = false
    rpc.request("test", {}, function(result)
      called = true
      assert.equals("ok", result.status)
    end)
    rpc.handle_line(vim.json.encode({ jsonrpc = "2.0", id = 1, result = { status = "ok" } }))
    assert.is_true(called)
  end)
end)

describe("cursor.context", function()
  it("builds lean prompts", function()
    local context = require("cursor.context")
    local prompt = context.build_prompt("explain", {
      file = "/repo/foo.go",
      cwd = "/repo",
      cursor = { line = 10, column = 5 },
    })
    assert.truthy(prompt:find("explain"))
    assert.truthy(prompt:find("foo.go"))
    assert.is_false(prompt:find("never"))
  end)
end)

describe("cursor.project", function()
  it("checks within root", function()
    local project = require("cursor.project")
    assert.is_true(project.within_root("/repo/src/foo.go", "/repo"))
    assert.is_false(project.within_root("/other/foo.go", "/repo"))
  end)
end)

describe("cursor.usage", function()
  it("rejects empty prompts", function()
    local usage = require("cursor.usage")
    local ok = usage.validate_prompt("")
    assert.is_false(ok)
  end)
end)
